### ISSUE TITLE
为什么没有DEIS的结果的

### ISSUE THREAD

**Issue by YuChen-Liang** [zju-pi/Diff-Master#3]

**Comment by YuChen-Liang** [comment]
另外iPNDM指的是AB算法吗，原论文里的iPNDM似乎只能用于linear schedule

**Comment by zhyzhouu** [comment]
我们复现了DEIS (tAB and rhoAB)，复现结果稍好于原论文报告的结果，但不如ipndm；我们同样实现了变步长的AB算法，但效果不如等步长的情况。代码进一步整理好之后会开源。

**Comment by YuChen-Liang** [comment]
> 我们复现了DEIS (tAB and rhoAB)，复现结果稍好于原论文报告的结果，但不如ipndm；我们同样实现了变步长的AB算法，但效果不如等步长的情况。代码进一步整理好之后会开源。

所以iPNDM就是等步长的AB是么？论文里并没有提及iPNDM的schedule,采用的是等步长的schedule，还是直接套用系数到polynomial schedule呢？

**Comment by zhyzhouu** [comment]
> > 我们复现了DEIS (tAB and rhoAB)，复现结果稍好于原论文报告的结果，但不如ipndm；我们同样实现了变步长的AB算法，但效果不如等步长的情况。代码进一步整理好之后会开源。
> 
> 所以iPNDM就是等步长的AB是么？论文里并没有提及iPNDM的schedule,采用的是等步长的schedule，还是直接套用系数到polynomial schedule呢？

是的。我们套用AB的系数用在了polynomial schedule上，效果比各种schedule上变步长的AB算法都好。

**Comment by YuChen-Liang** [comment]
要开源了吗，网络架构和训练设置paper里一点没写啊，哈哈哈
